<a href="https://colab.research.google.com/github/Akhilesh1118/Python/blob/main/Lecture%207/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

## Learning Objectives

After completing this notebook, you will be able to:

- Create NumPy arrays
- Understand array properties
- Perform indexing and slicing
- Use vectorization and broadcasting
- Apply mathematical functions
- Work with multi-dimensional arrays

# 1. NumPy
- NumPy is the fundamental package for scientific    computing with Python.
-  It is designed for fast numerical computing.

# 2. Python Lists vs NumPy Arrays
1. NumPy arrays are faster (optimized in C)
2. NumPy stores data in continuous memory blocks
3. Uses less memory (optimized storage)
4. Built-in mathematical functions
5. Supports direct vectorized operations.

# 3. So Why is NumPy faster ?
- Homogeneous Data Types and Contiguous Memory (same data type )
- Vector Operations & C implementation
- Reduced Overhead


---

In [2]:
import numpy as np
import time

In [3]:
# execution performance
size = 10_000_000

# python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

# numpy arrays.
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time =  {end-start} seconds" )



python list time = 0.9390313625335693 seconds
numpy array time =  0.038735389709472656 seconds


In [66]:
# memory
import sys

print(f"python list size = {sys.getsizeof(py_list)} bytes")

print(f"numpy array size = {np_arr.nbytes}  bytes")

python list size = 80000056 bytes
numpy array size = 80000000  bytes


In [17]:
# create - from lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.dtype)

arr2 = np.array([1,2,3,4,5,"prime" ])
print(arr2, type(arr2), arr2.dtype ,  arr2.shape)

arr2D = np.array([ [1,2,3,13] , [4,5,6,14], [7,8,9,16], [10,11,12,18] ])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3 13]
 [ 4  5  6 14]
 [ 7  8  9 16]
 [10 11 12 18]] (4, 4)


# 4. Shape Attribute

The `shape` attribute returns the dimensions of an array.

Formula:

(rows × columns)

In [21]:
# CREATE
arr1 = np.zeros((2,3), dtype="int64") # prefill
print(arr1, arr1.shape)

arr2 = np.ones((2, 3)) # prefill
print(arr2, arr2.shape)

arr3 = np.full((3 , 4), 100) # prefill with val
print(arr3, arr3.shape)

arr4 = np.eye((3)) # identity matrix
print(arr4, arr4.shape)

# range(start, end, step)
arr5 = np.arange(0,11,2) # range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 3 ) # evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.   50.5 100. ] (3,)


In [64]:
# Properties
arr1D = np.array([1,2,3,4,5])
arr2D = np.array([ [1,2,3] , [4,5,6] , [7,8,9],[12,13,14 ]])

print(f"1D array shape {arr1D.shape} " )
print(f"2D array shape {arr2D.shape} " )

print(arr1D.dtype) # it is used to print the type of numpy
print(arr2D.ndim) # print number of dimension value

float_arr = arr1D.astype(np.float64)  # Change data type int into float
print(float_arr, float_arr.dtype)

1D array shape (5,) 
2D array shape (4, 3) 
int64
2
[1. 2. 3. 4. 5.] float64


# 5. NumPy
Operations on NumPy Arrays
- Reshaping
- Indexing(1D & 2D array)
- Fancy & Boolean Indexing

In [ ]:
# Operations on arrays.

arr = np.array([[1,2,3], [4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2))
print(reshaped, reshaped.shape)

flattened = arr.flatten() # 2D = > 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [ ]:
# Indexing
arr1D = np.array([1,2,3,4,5])
arr2D = np.array([ [1,2,3] , [4,5,6] , [7,8,9],[12,13,14 ]])

print(arr1D[0])
print(arr1D[2])

print(arr2D[0] [2] )
print(arr2D[1] [0] )



1
3
3
4


In [ ]:
# Fancy Indexing .
arr = np.array([1,2,3,4,5])

idx = [0,1,3]
print(arr[idx])

[1 2 4]


In [ ]:
# Boolean Indexing.
arr = np.array([1,2,3,4,5])

print(arr[arr>2])
print(arr[arr%2 == 0])
print(arr[arr%2 != 0  ])


[3 4 5]
[2 4]
[1 3 5]


In [25]:
# Slicing
arr = np.array([1,2,3,4,5])

print(arr[1:4]) #[start, end, step]
print(arr[1:])
print(arr[::2])


[2 3 4]
[2 3 4 5]
[1 3 5]


In [ ]:
# Copy vs View.
nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200

print(sub_list)
print(nums)
print("Difference b/w List or NumPy")
arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
# sub_arr = arr[1:3].copy() When we use copy() original change  not reflect in the original array
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)
print(arr)


[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
Difference b/w List or NumPy
[2 3]
[200   3]
[  1 200   3   4   5]


# 6. NumPy
Common Data Types

- Integers: **int32**,**int64**
- Floating point nums: **float32**,**float64**
- Boolean: **bool**
- Complex nums: **complex64**, **complex128**
- String: **S**(byte-str) & **U** (unicode-str)
- Object: generic python objects - **object**

In [28]:
# Data Types

arr = np.array([1,2,3,4,5,"John"])
print(arr, arr.dtype)

['1' '2' '3' '4' '5' 'John'] <U21


In [ ]:
# Axes in Multi-dimensional arrays
arr2D = np.array([ [1,2,3] , [4,5,6] , [7,8,9],[12,13,14 ] ])
print(arr2D)

print(f"Sum of all the element  {np.sum(arr2D)}")

sum_of_columns = np.sum(arr2D, axis = 0)
print(f"Sum of all three column {sum_of_columns}")

sum_of_rows = np.sum(arr2D, axis = 1)
print(f"Sum of all three row wise {sum_of_rows}")

# slicing
print(arr2D[0:2, 1:2] )


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [12 13 14]]
Sum of all the element  84
Sum of all three column [24 28 32]
Sum of all three row wise [ 6 15 24 39]
[[2]
 [5]]


In [ ]:
# 3D array

arr3D = np.array([[[1, 2],[3, 4],[5, 6]], [[7, 8],[9, 10],[11, 12]]])
print(arr3D, arr3D.shape)
# Indexing
print(arr3D[0][1][1]) # 4
print(arr3D[1][2][1]) # 12
print(arr3D[:, :, 0])  # first col from both layers
print(arr3D[:, 0, :])  # first row from both layers
# Manipulating data
arr3D[:, 0, :] = 99
# change first row to store 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
12
[[ 1  3  5]
 [ 7  9 11]]
[[1 2]
 [7 8]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


# 7. Vectorization and Broadcasting

In [37]:
# vectorization

arr = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])

print(arr ** 2) # print the square of each element present in list
print(arr + arr2)

[ 1  4  9 16 25]
[ 2  4  6  8 10]


In [40]:
# Broadcasting - scaling our program

arr = np.array([1,2,3,4,5])
arr2 = np.array([ [1,2,3,4,5], [1,2,3,4,5] ])

print(arr.shape)
print(arr2.shape)
print(arr + arr2)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


### 7.1 **Vector Normalization** - Normalizing an array means transforming its values so they fit into a specific scale or range

### Standardization Formula

(data - mean) / standard deviation

This transforms data to have:
- Mean = 0
- Standard Deviation = 1

In [43]:
# normalize

arr = np.array([[1,2] ,[3,4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


# 8. NumPy - Important Mathematical Functions

---

## 1. Aggregation Functions

Aggregation functions are used to summarize data.

### `np.sum()`
Returns the sum of all elements.

### `np.prod()`
Returns the product of all elements.

### `np.min()`
Returns the minimum value.

### `np.max()`
Returns the maximum value.

### `np.mean()`
Returns the average value.

### `np.std()`
Returns the standard deviation.

### `np.var()`
Returns the variance.

### `np.median()`
Returns the median value.

### `np.argmin()`
Returns the index of the minimum value.

### `np.argmax()`
Returns the index of the maximum value.

---

## 2. Power Functions

Power functions are used for square, square root, and exponent calculations.

### `np.square()`
Returns the square of each element.

### `np.sqrt()`
Returns the square root of each element.

### `np.power(a, b)`
Raises `a` to the power `b`.

---

## 3. Logarithmic & Exponential Functions

These functions are commonly used in mathematics and data science.

### `np.log()`
Natural logarithm (Base e).

### `np.log10()`
Logarithm with base 10.

### `np.log2()`
Logarithm with base 2.

### `np.exp()`
Calculates e raised to the power x.

---

## 4. Rounding Functions

Used to round decimal values.

### `np.round()`
Rounds to the nearest value.

### `np.floor()`
Rounds down to the nearest integer.

### `np.ceil()`
Rounds up to the nearest integer.

### `np.trunc()`
Removes the decimal part.

---

## 5. Extra Useful Functions

### `np.unique()`
Returns unique values from an array.

### `np.sort()`
Sorts the array in ascending order.

### `np.abs()`
Returns the absolute value.


In [47]:
# Mathematical Functions

# aggregation

arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.max(arr))
print(np.argmax(arr))
print(np.min(arr))
print(np.argmin(arr))


15
120
5
4
1
0


In [51]:
# Power function
arr = np.array([1,2,3,4,5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [55]:
# log

arr = np.array([1,2,3,4,5])

print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [63]:
# Rounding

print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

arr = np.array([1,2,3,4,22,2,1,4,5])

print(np.unique(arr))
print(np.sort(arr))

print(np.abs(arr))

3.0
4.0
3.0
3.0
[ 1  2  3  4  5 22]
[ 1  1  2  2  3  4  4  5 22]
[ 1  2  3  4 22  2  1  4  5]


---

# Summary

In this notebook, we learned:

✅ NumPy Arrays

✅ Array Creation

✅ Array Properties

✅ Indexing & Slicing

✅ Fancy & Boolean Indexing

✅ Data Types

✅ Vectorization

✅ Broadcasting

✅ Mathematical Functions

---

# Key Takeaways

- NumPy provides efficient numerical computation.
- NumPy arrays are faster and more memory-efficient than Python lists.
- Broadcasting allows operations between arrays of different shapes.
- Vectorization improves performance by avoiding explicit loops.
- NumPy offers powerful mathematical and statistical functions.